## Advanced Numpy

import numpy as np

### 1. Reshape
Reshaping allows you to change the shape of an array without changing its data.

In [4]:
# Create a 1D array
arr = np.arange(12)

# Reshape to 2D array (3x4)
# arr.reshape(3, 4) changes the shape of the array to 3 rows and 4 columns.
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 2. Concatenate
Concatenation joins two or more arrays along an existing axis.

In [6]:
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
concat_arr = np.concatenate((arr1, arr2), axis=0)
print(concat_arr)

# Concatenate along columns (axis=1)
concat_arr_col = np.concatenate((arr1, arr2), axis=1)
print(concat_arr_col)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Explanation:

- axis=0 concatenates arrays along rows.
- axis=1 concatenates arrays along columns.

### 3. Splitting
Splitting divides an array into multiple sub-arrays.

In [7]:
# Create a 1D array
arr = np.arange(9)

# Split into 3 equal parts
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


### 4. Horizontal Split (hsplit)
hsplit splits an array horizontally (column-wise).

In [8]:
# Create a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Horizontal split into 2 equal parts
h_split_arr = np.hsplit(arr, 2)
print(h_split_arr)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### 5. Vertical Split (vsplit)
vsplit splits an array vertically (row-wise).

In [9]:
# Create a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Vertical split into 2 equal parts
v_split_arr = np.vsplit(arr, 2)
print(v_split_arr)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### 6. Stacking
Stacking joins arrays along a new axis.

In [10]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack along rows
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

# Stack along columns
stacked_arr_col = np.stack((arr1, arr2), axis=1)
print(stacked_arr_col)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Explanation:

- np.stack((arr1, arr2), axis=0) stacks arrays along a new row axis.
- np.stack((arr1, arr2), axis=1) stacks arrays along a new column axis.

### 7. Transpose
Transpose switches the axes of an array.

In [11]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


Explanation:

- arr.T swaps the rows and columns.arr)


### 8. Broadcasting
Broadcasting allows arithmetic operations on arrays of different shapes.

In [12]:
# Create two arrays of different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

# Add arrays using broadcasting
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


Explanation:

- The smaller array arr2 is broadcasted across arr1, adding element-wise.

### 9. Element-wise Operations
Perform operations on elements of arrays.

In [13]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Add 10 to each element
added_arr = arr + 10
print(added_arr)

# Square each element
squared_arr = arr ** 2
print(squared_arr)

[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [16 25 36]]


### 10. Advanced Indexing
Select elements using advanced indexing techniques.

In [14]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select elements at (0,1), (1,2), and (2,0)
selected_elements = arr[[0, 1, 2], [1, 2, 0]]
print(selected_elements)

[2 6 7]
