# Tensors

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second order tensor.

In [12]:
from numpy import array, tensordot

In [5]:
T = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]],
])

In [6]:
print(T.shape)

(3, 3, 3)


## 1. Tensor Addition

In [7]:
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


## 2. Tensor Subtraction

In [9]:
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## 3. Tensor Hadamard Product

In [10]:
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


## 4. Tensor Division

In [11]:
C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## 5. Tensor Product

In [13]:
A = array([1,2])
B = array([3,4])
C = tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]


# Neural Networks

### a. What is a Neural Network?
Neural networks are designed to recognize patterns.
They are made up of layers of neurons (also called nodes), similar to the neurons in the human brain.

### b. Basic Structure of a Neural Network

**Input Layer:**
This is where the data enters the network.
Each neuron in this layer represents a feature of the data (e.g., pixel value in an image, or a word in a sentence).

**Hidden Layers:**
These layers are where the actual computation happens.
Neurons in hidden layers receive input from the previous layer, process it, and pass it to the next layer.

**Output Layer:**
This layer produces the final result or prediction.
The number of neurons here corresponds to the number of possible outcomes (e.g., types of objects in an image).

### c. How Does It Work?

**Weights:**
Connections between neurons have weights, which determine the importance of each input.
Weights are adjusted during training to make accurate predictions.

**Bias:**
Bias is an extra parameter that helps the model make better predictions by shifting the output of neurons.

**Activation Function:**
After receiving inputs, each neuron applies an activation function.
This function decides if the neuron should be "activated" or not, meaning it decides whether to pass the information forward.

### d. Training a Neural Network

**Forward Propagation:**
Data moves from the input layer, through hidden layers, to the output layer.
The output is compared with the actual answer to see how close it is.

**Loss Function:**
This measures how far the network's prediction is from the actual answer.
The goal is to minimize this difference.

**Backpropagation:**
The network learns by adjusting the weights and biases based on the error.
This process repeats until the network makes accurate predictions.